### ISSUE TITLE
System.ArgumentException: Supplied slot is not part of this inventory

### ISSUE THREAD

**Issue by bluelightning32** [bluelightning32/vs-gourmand#4]
Reported by Kattifnatt on moddb.
```
Running on 64 bit Windows 10.0.22631.0 with 32620 MB RAM
Game Version: v1.19.8 (Stable)
2024-10-09 01:29:20: Critical error occurred in the following mod: [gourmand@1.2.3](mailto:gourmand@1.2.3)
Loaded Mods: [acorns@0.5.3](mailto:acorns@0.5.3), [aculinaryartillery@1.1.4](mailto:aculinaryartillery@1.1.4), [irregularguybetterjam@1.0.0](mailto:irregularguybetterjam@1.0.0), [chiseltools@1.11.3](mailto:chiseltools@1.11.3), [distillationinfo@1.0.0](mailto:distillationinfo@1.0.0), [hqzlights@1.1.1](mailto:hqzlights@1.1.1), [geodesandgemstones@1.1.1](mailto:geodesandgemstones@1.1.1), [hideandfabric@1.3.0](mailto:hideandfabric@1.3.0), [mycodiversity@1.0.1](mailto:mycodiversity@1.0.1), [nailsmold@1.0.1](mailto:nailsmold@1.0.1), [oils@1.2.2](mailto:oils@1.2.2), [plumpkins@1.0.3](mailto:plumpkins@1.0.3), [primitivesurvival@3.5.2](mailto:primitivesurvival@3.5.2), [roas@1.0.0](mailto:roas@1.0.0), [she1fish@1.2.0](mailto:she1fish@1.2.0), [visibleore@1.0.1](mailto:visibleore@1.0.1), [game@1.19.8](mailto:game@1.19.8), [vtr@1.0.1](mailto:vtr@1.0.1), [wlts@1.0.0](mailto:wlts@1.0.0), [ancienttools@1.5.18](mailto:ancienttools@1.5.18), [animalcages@3.0.2](mailto:animalcages@3.0.2), [egocaribautomapmarkers@3.1.0](mailto:egocaribautomapmarkers@3.1.0), [betterfirepit@1.1.4](mailto:betterfirepit@1.1.4), [betterhoe@1.1.2](mailto:betterhoe@1.1.2), [butterflycases@1.0.1](mailto:butterflycases@1.0.1), [carryon@1.7.4](mailto:carryon@1.7.4), [commonlib@2.3.7](mailto:commonlib@2.3.7), [expandedfoods@1.6.9](mailto:expandedfoods@1.6.9), [foodshelves@1.3.1](mailto:foodshelves@1.3.1), [fromgoldencombs@1.5.1](mailto:fromgoldencombs@1.5.1), [gourmand@1.2.3](mailto:gourmand@1.2.3), [hudclock@3.4.0](mailto:hudclock@3.4.0), [sailboat@1.3.0](mailto:sailboat@1.3.0), [levelup@1.2.5](mailto:levelup@1.2.5), [manualdough@1.0.2](mailto:manualdough@1.0.2), [moreanimals@1.3.3](mailto:moreanimals@1.3.3), [spearexpantion@0.1.4](mailto:spearexpantion@0.1.4), [petai@2.2.4](mailto:petai@2.2.4), [claywheel@1.1.1](mailto:claywheel@1.1.1), [prospecttogether@1.3.0](mailto:prospecttogether@1.3.0), [rivers@2.7.0](mailto:rivers@2.7.0), [scythemold@1.0.1](mailto:scythemold@1.0.1), [creative@1.19.8](mailto:creative@1.19.8), [vsimgui@1.1.3](mailto:vsimgui@1.1.3), [survival@1.19.8](mailto:survival@1.19.8), [workbenchexpansion@1.8.0](mailto:workbenchexpansion@1.8.0), [configlib@1.3.5](mailto:configlib@1.3.5), [em@2.6.3](mailto:em@2.6.3), [kevinsfurniture@1.0.0](mailto:kevinsfurniture@1.0.0), [playercorpse@1.9.0](mailto:playercorpse@1.9.0), [shearlib@1.0.0](mailto:shearlib@1.0.0), [slanted_display_cases@1.3.2](mailto:slanted_display_cases@1.3.2), [stonequarry@3.2.1](mailto:stonequarry@3.2.1), [xinvtweaks@1.6.1](mailto:xinvtweaks@1.6.1), [statushudcont@2.1.1](mailto:statushudcont@2.1.1), [tailorsdelight@1.5.8](mailto:tailorsdelight@1.5.8), [wool@1.2.0](mailto:wool@1.2.0), [upholstery@1.0.0](mailto:upholstery@1.0.0)
System.ArgumentException: Supplied slot is not part of this inventory (dummy-1784)!
at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 480
at Vintagestory.API.Common.ItemSlot.MarkDirty() in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 456
at Vintagestory.GameContent.BlockMeal.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VSSurvivalMod\Systems\Cooking\BlockMeal.cs:line 871
at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionState(IWorldAccessor world, ItemSlot inslot, EnumTransitionType type) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2403
at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 274
at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 211
at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 484
at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
at Gourmand.Gui.GuiDialogPatch.OnRenderGUI(GuiDialogCharacter __instance, Single deltaTime, Int32& ___curTab, Matrixf& ___mat, Vec4f& ___lighPos, ElementBounds& ___insetSlotBounds, Single& ___yaw, Boolean& ___rotateCharacter)
at Vintagestory.Client.NoObf.GuiDialogCharacter.OnRenderGUI_Patch1(GuiDialogCharacter this, Single deltaTime)
at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
at OpenTK.Windowing.Desktop.GameWindow.Run()
at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by bluelightning32** [comment]
I reproduced it with gourmand, aculinaryartillery, and expandedfoods. Note that these are old versions of those mods. I matched the versions used by the bug reporter.
```
Running on 64 bit Linux (Fedora Linux 40 (Workstation Edition)) [Kernel 6.10.11.200] with 11797 MB RAM
Game Version: v1.19.8 (Stable)
10/8/2024 7:33:34PM: Critical error occurred in the following mod: gourmand@1.2.3
Loaded Mods: aculinaryartillery@1.1.4, game@1.19.8, expandedfoods@1.6.9, gourmand@1.2.3, creative@1.19.8, survival@1.19.8
System.ArgumentException: Supplied slot is not part of this inventory (dummy-769)!
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 480
   at Vintagestory.API.Common.ItemSlot.MarkDirty() in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 449
   at Vintagestory.GameContent.BlockMeal.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VSSurvivalMod\Systems\Cooking\BlockMeal.cs:line 871
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionState(IWorldAccessor world, ItemSlot inslot, EnumTransitionType type) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2403
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 189
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 273
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 211
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 484
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Gourmand.Gui.GuiDialogPatch.OnRenderGUI(GuiDialogCharacter __instance, Single deltaTime, Int32& ___curTab, Matrixf& ___mat, Vec4f& ___lighPos, ElementBounds& ___insetSlotBounds, Single& ___yaw, Boolean& ___rotateCharacter) in /home/kyle/vintage_source/vs-gourmand/src/Gui/GuiRenderOrderPatch.cs:line 27
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnRenderGUI_Patch1(GuiDialogCharacter this, Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 102
   at Vintagestory.Client.ClientProgram..ctor(String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 47
   at VintagestoryClientLinux.ClientLinux.Main(String[] args) in VintagestoryClient\Linux\ClientLinux.cs:line 9
```

The debugger says that the DummyInventory's slot was somehow replaced with a regular ItemSlot? Yet the SlideshowItemstackTextComponent is still pointing to the original slot, which is a DummySlot.

**Comment by bluelightning32** [comment]
Apparently it's normal for the slot to be only partially connected to the inventory. This is where the slot is created in SlideshowItemstackTextComponent.cs:
```
    private void initSlot()
    {
        dummyInv = new DummyInventory(capi);
        dummyInv.OnAcquireTransitionSpeed = (EnumTransitionType transType, ItemStack stack, float mul) => 0f;
        slot = new DummySlot(null, dummyInv);
    }
```

The comment above DummySlot says it is not connected.
```
//
// Summary:
//     A single slot not attached to a given inventory.
```

So maybe the issue is that the food item tried to modify the dummy slot?
